package main;

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.awt.EventQueue;
import java.awt.FlowLayout;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;

import javax.swing.JTextPane;
import javax.swing.border.EmptyBorder;
import javax.swing.JInternalFrame;
import javax.swing.JTextField;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.JButton;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JComboBox;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;

public class Timetable extends JFrame {
	
	
	//create sql date and time types to compare in the query
	private static java.util.Date today = new java.util.Date();
	//private Time curTime = new Time(today.getTime());
	private static Date curDate = new Date(today.getTime());
	//TODO need to get a date for a week away and a month away
	
	
	//need to read this from a text file
	static String thisStop = "101";
	
	//prepare the query to get all of the bus routes that arrive at this stop
	private static String qryGetRouteNumsStart = "select distinct Route_ID, Route_Name from Arrival_Stop natural join Route natural join Arrival_Times where Stop_ID = ";
	private static String qryGetRouteNumsEnd = " and Arrival_Time >= '" ;//+ curDate + "'";

	
	//prepare the query that gets all of the times. this will be nested in a loop which goes through the IDs found in the previous query
	static String qryGetRoutes = "Select Arrival_time from Arrival_Stop natural join Route natural join Arrival_Times natural join Stop where Route_ID = ";
	
	//generated by windowBuilder
	private JPanel contentPane;

	
	public Timetable() {
		
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 1000, 500);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		contentPane.setLayout(null);
		
		JPanel panel = new JPanel();
		panel.setBounds(6, 6, 982, 466);
		contentPane.add(panel);
		
		JLabel lblNextBus = new JLabel("Next Bus: ?? Minutes");
		lblNextBus.setHorizontalAlignment(SwingConstants.CENTER);
		
		JTextPane txtpnTimes = new JTextPane();
		txtpnTimes.setText("");
		
		JButton btnDay = new JButton("Day");
		btnDay.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				getTimes(txtpnTimes, "1 DAY");
				
			}
		});
		
		JButton btnWeek = new JButton("Week");
		btnWeek.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {						 
				getTimes(txtpnTimes, "1 WEEK");
			}
		});
		
		JButton btnMonth = new JButton("Month");
		btnMonth.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				getTimes(txtpnTimes, "1 MONTH");
			}
		});
		
		
		
		
		JComboBox cmbRoutes = new JComboBox();
		
		JButton btnTemp = new JButton("temp");
		
		//start adding code here
		
		
		
		btnTemp.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				getTimes(txtpnTimes, "");
				
			}
		});

		getTimes(txtpnTimes, "");
				
		JButton btnRefresh = new JButton("refresh");
		btnRefresh.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				changeRouteNo(cmbRoutes);
				getTimes(txtpnTimes, "1 DAY");
			}
		});
		getStops(cmbRoutes);
		GroupLayout gl_panel = new GroupLayout(panel);
		gl_panel.setHorizontalGroup(
			gl_panel.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_panel.createSequentialGroup()
					.addGap(12)
					.addComponent(cmbRoutes, GroupLayout.PREFERRED_SIZE, 805, GroupLayout.PREFERRED_SIZE)
					.addGap(12)
					.addComponent(btnRefresh, GroupLayout.PREFERRED_SIZE, 141, GroupLayout.PREFERRED_SIZE))
				.addGroup(gl_panel.createSequentialGroup()
					.addGap(12)
					.addComponent(lblNextBus, GroupLayout.PREFERRED_SIZE, 958, GroupLayout.PREFERRED_SIZE))
				.addGroup(gl_panel.createSequentialGroup()
					.addGap(480)
					.addComponent(btnTemp, GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE)
					.addGap(12)
					.addComponent(btnDay, GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE)
					.addGap(7)
					.addComponent(btnWeek, GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE)
					.addGap(3)
					.addComponent(btnMonth, GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE))
				.addGroup(gl_panel.createSequentialGroup()
					.addGap(12)
					.addComponent(txtpnTimes, GroupLayout.PREFERRED_SIZE, 958, GroupLayout.PREFERRED_SIZE))
		);
		gl_panel.setVerticalGroup(
			gl_panel.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_panel.createSequentialGroup()
					.addGap(22)
					.addGroup(gl_panel.createParallelGroup(Alignment.LEADING)
						.addComponent(cmbRoutes, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnRefresh, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
					.addGap(45)
					.addComponent(lblNextBus, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
					.addGap(52)
					.addGroup(gl_panel.createParallelGroup(Alignment.LEADING)
						.addComponent(btnTemp, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnDay, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnWeek, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnMonth, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
					.addGap(12)
					.addComponent(txtpnTimes, GroupLayout.PREFERRED_SIZE, 236, GroupLayout.PREFERRED_SIZE))
		);
		panel.setLayout(gl_panel);
	}
	
	
	//show the window when this file is run
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					Timetable frame = new Timetable();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
		
	}
	
	private static String parseDate(String date) throws ParseException {
		SimpleDateFormat iso8601 = new SimpleDateFormat("yyyy-MM-dd");
		java.util.Date parsedDate = iso8601.parse(date);
		iso8601.applyPattern("EEE dd-MMM");
		String day = iso8601.format(parsedDate);
		System.out.println(day);
		return day;
	}
	
	/**
	 * 
	 * @param updPane the text pane to append the new text
	 * @param query the query to search
	 */
	public static void getTimes(JTextPane updPane, String constraints) {
		updPane.setText("");
		DatabaseConnection dbConn = new DatabaseConnection();
		dbConn.connect();
		String qryGetRouteNums = qryGetRouteNumsStart + thisStop;// + qryGetRouteNumsEnd + curDate + "'";
		ResultSet routeNumbers = dbConn.runQuery(qryGetRouteNums);
		String newTextField = "";
		String date = "";
		try {
			
			while (routeNumbers.next()) {
				newTextField += routeNumbers.getString("Route_Name") + ":\t";
				String qryGetTimes = qryGetRoutes +  routeNumbers.getInt("Route_ID") + " and Stop_ID = " + thisStop  + qryGetRouteNumsEnd + curDate + "'";
				if (constraints != "") {
					qryGetTimes += "and Arrival_Time <= (SELECT '" + curDate + "' + INTERVAL " + constraints +")";
				}
				qryGetTimes += " order by Arrival_Time ";
				ResultSet times = dbConn.runQuery(qryGetTimes);
				while (times.next()){
					try {
						date = parseDate(times.getDate("Arrival_Time").toString());
					} catch (ParseException e) {
						e.printStackTrace();
					}
					String out = date + " " + times.getTime("Arrival_Time").toString() + "  |  ";
					newTextField += out;
					//newTextField += times.getDate("Arrival_Time").toString() + " " + times.getTime("Arrival_Time").toString() + "\t";
					//newTextField += " " + times.getTime("Arrival_Time").toString() + "\t";

				}
				newTextField += "\n\n\n";
			}
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		updPane.setText(newTextField);
		dbConn.closeConnection();
	}
	
	public static void changeRouteNo(JComboBox cmb) {
		String qry = "Select distinct Stop_ID from Stop where Stop_Name = '" + cmb.getSelectedItem().toString() + "'";
		DatabaseConnection dbConn = new DatabaseConnection();
		dbConn.connect();
		ResultSet stopID = dbConn.runQuery(qry);
		String stop = thisStop;
		//System.out.println(stop);
		try {
			while (stopID.next()) {
				stop = stopID.getString("Stop_ID");
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		//System.out.println(stop);
		dbConn.closeConnection();
		thisStop = stop;
		
	}
	
	public static void getStops(JComboBox box) {
		String qry = "Select distinct * from Stop";
		String curStopName = "";
		DatabaseConnection dbConn = new DatabaseConnection();
		dbConn.connect();
		ResultSet stopNames = dbConn.runQuery(qry);
		try {
			while (stopNames.next()) {
				String curStopID = ""+stopNames.getInt("Stop_ID");
				String curStop = stopNames.getString("Stop_Name");
				box.addItem(curStop);
				if (curStopID.equals(thisStop)) {
					curStopName = curStop;
				}
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		dbConn.closeConnection();
		box.setSelectedItem(curStopName);
	}
}
